/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as CurrencyReportRouteImport } from './routes/currency-report'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsPairsRouteImport } from './routes/settings.pairs'
import { Route as ApiPublicBridgeTradesRouteImport } from './routes/api/public/bridge/trades'
import { Route as ApiPublicBridgePollRouteImport } from './routes/api/public/bridge/poll'
import { Route as ApiPublicBridgeExecution_logRouteImport } from './routes/api/public/bridge/execution_log'
import { Route as ApiPublicBridgeAccountRouteImport } from './routes/api/public/bridge/account'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyReportRoute = CurrencyReportRouteImport.update({
  id: '/currency-report',
  path: '/currency-report',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPairsRoute = SettingsPairsRouteImport.update({
  id: '/pairs',
  path: '/pairs',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiPublicBridgeTradesRoute = ApiPublicBridgeTradesRouteImport.update({
  id: '/api/public/bridge/trades',
  path: '/api/public/bridge/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgePollRoute = ApiPublicBridgePollRouteImport.update({
  id: '/api/public/bridge/poll',
  path: '/api/public/bridge/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeExecution_logRoute =
  ApiPublicBridgeExecution_logRouteImport.update({
    id: '/api/public/bridge/execution_log',
    path: '/api/public/bridge/execution_log',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBridgeAccountRoute = ApiPublicBridgeAccountRouteImport.update({
  id: '/api/public/bridge/account',
  path: '/api/public/bridge/account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/bridge': typeof BridgeRoute
  '/currency-report': typeof CurrencyReportRoute
  '/decisions': typeof DecisionsRoute
  '/positions': typeof PositionsRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/settings/pairs': typeof SettingsPairsRoute
  '/api/public/bridge/account': typeof ApiPublicBridgeAccountRoute
  '/api/public/bridge/execution_log': typeof ApiPublicBridgeExecution_logRoute
  '/api/public/bridge/poll': typeof ApiPublicBridgePollRoute
  '/api/public/bridge/trades': typeof ApiPublicBridgeTradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/bridge': typeof BridgeRoute
  '/currency-report': typeof CurrencyReportRoute
  '/decisions': typeof DecisionsRoute
  '/positions': typeof PositionsRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/settings/pairs': typeof SettingsPairsRoute
  '/api/public/bridge/account': typeof ApiPublicBridgeAccountRoute
  '/api/public/bridge/execution_log': typeof ApiPublicBridgeExecution_logRoute
  '/api/public/bridge/poll': typeof ApiPublicBridgePollRoute
  '/api/public/bridge/trades': typeof ApiPublicBridgeTradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/bridge': typeof BridgeRoute
  '/currency-report': typeof CurrencyReportRoute
  '/decisions': typeof DecisionsRoute
  '/positions': typeof PositionsRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signals': typeof SignalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/settings/pairs': typeof SettingsPairsRoute
  '/api/public/bridge/account': typeof ApiPublicBridgeAccountRoute
  '/api/public/bridge/execution_log': typeof ApiPublicBridgeExecution_logRoute
  '/api/public/bridge/poll': typeof ApiPublicBridgePollRoute
  '/api/public/bridge/trades': typeof ApiPublicBridgeTradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/backtest'
    | '/bridge'
    | '/currency-report'
    | '/decisions'
    | '/positions'
    | '/report'
    | '/settings'
    | '/signals'
    | '/sitemap.xml'
    | '/settings/pairs'
    | '/api/public/bridge/account'
    | '/api/public/bridge/execution_log'
    | '/api/public/bridge/poll'
    | '/api/public/bridge/trades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/backtest'
    | '/bridge'
    | '/currency-report'
    | '/decisions'
    | '/positions'
    | '/report'
    | '/settings'
    | '/signals'
    | '/sitemap.xml'
    | '/settings/pairs'
    | '/api/public/bridge/account'
    | '/api/public/bridge/execution_log'
    | '/api/public/bridge/poll'
    | '/api/public/bridge/trades'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/backtest'
    | '/bridge'
    | '/currency-report'
    | '/decisions'
    | '/positions'
    | '/report'
    | '/settings'
    | '/signals'
    | '/sitemap.xml'
    | '/settings/pairs'
    | '/api/public/bridge/account'
    | '/api/public/bridge/execution_log'
    | '/api/public/bridge/poll'
    | '/api/public/bridge/trades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BacktestRoute: typeof BacktestRoute
  BridgeRoute: typeof BridgeRoute
  CurrencyReportRoute: typeof CurrencyReportRoute
  DecisionsRoute: typeof DecisionsRoute
  PositionsRoute: typeof PositionsRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignalsRoute: typeof SignalsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicBridgeAccountRoute: typeof ApiPublicBridgeAccountRoute
  ApiPublicBridgeExecution_logRoute: typeof ApiPublicBridgeExecution_logRoute
  ApiPublicBridgePollRoute: typeof ApiPublicBridgePollRoute
  ApiPublicBridgeTradesRoute: typeof ApiPublicBridgeTradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency-report': {
      id: '/currency-report'
      path: '/currency-report'
      fullPath: '/currency-report'
      preLoaderRoute: typeof CurrencyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/pairs': {
      id: '/settings/pairs'
      path: '/pairs'
      fullPath: '/settings/pairs'
      preLoaderRoute: typeof SettingsPairsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/public/bridge/trades': {
      id: '/api/public/bridge/trades'
      path: '/api/public/bridge/trades'
      fullPath: '/api/public/bridge/trades'
      preLoaderRoute: typeof ApiPublicBridgeTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/poll': {
      id: '/api/public/bridge/poll'
      path: '/api/public/bridge/poll'
      fullPath: '/api/public/bridge/poll'
      preLoaderRoute: typeof ApiPublicBridgePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/execution_log': {
      id: '/api/public/bridge/execution_log'
      path: '/api/public/bridge/execution_log'
      fullPath: '/api/public/bridge/execution_log'
      preLoaderRoute: typeof ApiPublicBridgeExecution_logRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/account': {
      id: '/api/public/bridge/account'
      path: '/api/public/bridge/account'
      fullPath: '/api/public/bridge/account'
      preLoaderRoute: typeof ApiPublicBridgeAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsPairsRoute: typeof SettingsPairsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsPairsRoute: SettingsPairsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BacktestRoute: BacktestRoute,
  BridgeRoute: BridgeRoute,
  CurrencyReportRoute: CurrencyReportRoute,
  DecisionsRoute: DecisionsRoute,
  PositionsRoute: PositionsRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignalsRoute: SignalsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicBridgeAccountRoute: ApiPublicBridgeAccountRoute,
  ApiPublicBridgeExecution_logRoute: ApiPublicBridgeExecution_logRoute,
  ApiPublicBridgePollRoute: ApiPublicBridgePollRoute,
  ApiPublicBridgeTradesRoute: ApiPublicBridgeTradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
